name: Slack Version Notify

inputs:
  PACKAGE_VERSION:
    required: true
  SLACK_TOKEN:
    required: true
  SLACK_CHANNELS:
    required: true

runs:
  using: "composite"
  steps:
    - run: bash "./../scripts/slack-notify.sh"
      shell: bash
