name: Validate user permissions 

runs:
  using: "composite"
  steps:
    - run: |
            if [[ ${{ env.config_users }} != *"${{ github.actor }}"* ]];then
               echo "::error::No permission to deploy"
            fi
      shell: bash



  
