name: Validate user permissions 

inputs:
  ACTOR:
    required: true  
  
runs:
  using: "composite"
  steps:
    - run: |
            if [[ "${{inputs.ACTOR}}" != "" ]]; then
              echo "user ${{inputs.ACTOR}} has NO permissions to deploy"
              exit 0
            fi
            echo "user ${{inputs.ACTOR}} has permissions to deploy"



  
