name: Bump version

inputs:
  MAINTAIN_TOKEN:
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
    - name: Checkout next release branch
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.MAINTAIN_TOKEN }}
        ref: ${{ env.RELEASE_BRANCH }}
    - run: |
            npm install --no-package-lock --no-save semver@7.3.4
            PREV_PACKAGE_VERSION=$(node -p "require('./package.json').last_beta_version")
            NEW_PACKAGE_VERSION=$(node ./.github/scripts/update-prerelease-version.js beta)
            PACKAGE_VERSION=$(node -p "require('./package.json').last_beta_version")

            if [[ $PACKAGE_VERSION == *beta1 ]]
            then
              PREV_PACKAGE_VERSION=$(node -p "require('./package.json').version")
            fi

            echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
            echo "PACKAGE_VERSION : ${PACKAGE_VERSION}"
            echo "::set-output name=prev_version::${PREV_PACKAGE_VERSION}"
      shell: bash
