name: Get release branch name

runs:
  using: "composite"
  steps:
    - run: |
            if [ -z "$INPUT_VERSION" ];
              then
                PACKAGE_VERSION=$(node -p "require('./package.json').version")
                npm install --no-package-lock --no-save semver@7.3.4
                NEXT_PACKAGE_VERSION=$(npx semver $PACKAGE_VERSION -i minor)
                RELEASE_BRANCH="release/${NEXT_PACKAGE_VERSION}"
              else
                echo "Version var is set to ${INPUT_VERSION}"
                RELEASE_BRANCH="release/${INPUT_VERSION}"
              fi
              echo "RELEASE_BRANCH=${RELEASE_BRANCH}" >> $GITHUB_ENV
      shell: bash
      env:
          PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
          SLACK_TOKEN: ${{ inputs.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ inputs.SLACK_CHANNELS }}
          TEST_PERMISSIONS : "1"
