name: Publish Cloud Version

on: [push, pull_request, workflow_dispatch]
jobs:
  publish-to-cloud:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: get configuration
        id: configuration
        uses: antifree/json-to-variables@v1.0.1
        with: 
            filename: './.github/workflows/config.json'
            prefix: config
      - name: Test permissions
        uses: ./.github/workflows/permissions
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Checkout next release branch
        uses: ./.github/workflows/checkout-next-release-branch

#       - name: Send slack message
#         uses: ./.github/workflows/slack-notify
#         with:
#           PACKAGE_VERSION: "TEST"
#           SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
#           SLACK_CHANNELS: ${{ 'C03PMU9HK24' }}
