name: Publish Cloud Version

on: [push, pull_request, workflow_dispatch]
jobs:
  get-config:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: get configuration
        id: configuration
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: './.github/workflows/config.json'
  poc-job:
    needs: get-config
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Test permissions
        run: "echo ${{steps.configuration.outputs.users}}"
      - name: Send slack message
        uses: ./.github/workflows/slack-notify
        with:
          PACKAGE_VERSION: ${{ 'test version 123' }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ 'C03PMU9HK24' }}
